decert-me/backend-go

.gitignore
config/config.demo.yaml
internal/app/config/config.go
internal/app/config/quest.go
internal/app/dao/quest.go
internal/app/model/quest.go
internal/app/model/request/badge.go
internal/app/service/badge.go
internal/app/service/blockchain/quest.go
internal/app/service/blockchain/quest_minter_test.go
internal/app/service/quest.go
internal/app/utils/answer.go
internal/app/utils/answer_test.go
internal/app/utils/ipfs.go

add: 校验答案和分数

---

internal/app/dao/users.go

fix: 过期时间错误

---

internal/app/api/v1/challenge.go
internal/app/api/v1/ipfs.go
internal/app/cmd/config.demo.yaml
internal/app/cmd/locale.json
internal/app/config/config.go
internal/app/config/ipfs.go
internal/app/config/local.go
internal/app/dao/quest.go
internal/app/dao/user_challenge_log.go
internal/app/initialize/gorm.go
internal/app/middleware/auth.go
internal/app/model/quest.go
internal/app/model/request/challenge.go
internal/app/model/response/ipfs.go
internal/app/model/user_challenge_log.go
internal/app/router/challenge.go
internal/app/router/ipfs.go
internal/app/router/router.go
internal/app/service/challenge.go
internal/app/service/ipfs.go
internal/app/utils/answer.go
internal/app/utils/slice.go
internal/job/service/transaction.go

Add  IPFS 上传接口

---

internal/app/api/v1/challenge.go
internal/app/dao/user_challenge_log.go
internal/app/initialize/gorm.go
internal/app/model/quest.go
internal/app/model/request/challenge.go
internal/app/model/user_challenge_log.go
internal/app/router/challenge.go
internal/app/router/router.go
internal/app/service/challenge.go
internal/app/utils/answer.go

Add user challenge log

---

internal/app/api/v1/transaction.go
internal/app/model/quest.go
internal/app/model/request/transaction.go
internal/app/model/transaction.go
internal/app/service/transaction.go
internal/job/cmd/config.demo.yaml
internal/job/service/quest.go

[保存推荐内容](https://github.com/decert-me/backend-go/commit/b0edd6af4b2ca8a496712d797d27272c51cbeddf)

Feature Recommend

---

internal/job/dao/transaction.go

Fix QueryTransactionByHash函数多余

Fix QueryTransactionByHash函数多余

---

internal/job/service/quest_minter.go

Fix 空投过程 Claim 显示两条记录

---

internal/app/service/answer.go

Fix  获取 JSON 错误

---

internal/app/service/ipfs.go
internal/job/cmd/config.demo.yaml
internal/job/config/config.go
internal/job/config/ipfs.go
internal/job/service/badge.go
internal/job/service/ipfs.go
internal/job/service/quest.go

Fix IPFS 函数缺失

---

internal/app/api/v1/quest.go
internal/app/dao/quest.go
internal/app/model/response/quest.go
internal/app/service/quest.go

Feature Quest claimed

---

internal/app/dao/ens.go
internal/app/initialize/gorm.go
internal/app/model/ens.go
internal/app/service/ens.go

En 数据库缓存ENS数据

---

internal/app/api/v1/quest.go
internal/app/dao/quest.go
internal/app/model/response/quest.go
internal/app/router/quest.go
internal/app/service/quest.go

[添加查询挑战用户接口](https://github.com/decert-me/backend-go/commit/719c59df6e75cd4cdba42a165ee45a4ee166e558)

Feature 添加查询挑战用户接口

---

internal/job/service/quest.go

Fix 推荐显示格式错误

---

internal/app/dao/quest.go
internal/app/model/quest.go
internal/app/service/answer.go
internal/app/service/badge.go
internal/app/service/challenge.go
internal/app/service/quest.go
internal/app/utils/answer.go
internal/job/service/quest.go

Feature IPFS MetaData JSON

---

internal/app/dao/user_challenges.go

Fix 个人页面挑战排序错误

---

internal/job/service/quest_minter.go

EN 优化空投失败提示

---

internal/app/dao/quest.go

EN 优化挑战记录排序

---

internal/job/service/badge.go

FIX 修复JSON v1.1 更新 URI 错误

---

internal/app/dao/user_challenges.go

FIX 获取错误挑战记录

---

internal/job/cmd/config.demo.yaml
internal/job/config/twitter.go
internal/job/utils/twitter.go

EN 判断推文有效性逻辑调整

---

internal/job/cmd/main.go
internal/job/service/service.go

Fix 定时任务退出等待完成

---

internal/app/api/v1/ipfs.go
internal/app/model/request/ipfs.go
internal/app/service/ipfs.go
internal/app/service/service.go
internal/app/utils/answer_test.go
internal/app/utils/verify.go

Add JSON格式校验

---

internal/app/dao/user_challenges.go

Fix: 事务未提交

---

internal/judge/service/command.go
internal/judge/service/docker.go

Fix  docker zombie 进程

---

internal/app/api/v1/badge.go
internal/app/cmd/locale.json
internal/app/model/request/badge.go
internal/app/service/badge.go
internal/job/service/quest.go

Fix 修复修改题目部分内容未更新

---

internal/app/dao/user_challenges.go

Fix 修复临时表不及时释放

---

internal/app/api/v1/quest.go
internal/app/dao/quest.go
internal/app/model/request/quest.go
internal/app/router/quest.go
internal/app/service/quest.go

Add 添加修改recommend接口

---

internal/app/api/v1/user.go
internal/app/dao/quest.go
internal/app/model/response/user.go
internal/app/service/quest.go

Add 添加Quest已领取过SBT状态

---

internal/app/api/v1/meta.go
internal/app/cmd/config.demo.yaml
internal/app/config/system.go
internal/app/router/router.go
internal/app/service/meta.go

Add 添加代理Quest页面，修改meta功能

---

internal/job/dao/discord.go

EN 修改机器人名称

---

internal/job/dao/claim_badge_tweet.go

Fix 修复 claim 出现错误空投提醒

---

internal/app/api/v1/tutorial.go
internal/app/dao/tutorial.go
internal/app/initialize/gorm.go
internal/app/middleware/auth.go
internal/app/model/read_progress.go
internal/app/model/request/tutorial.go
internal/app/router/router.go
internal/app/router/tutorial.go
internal/app/service/tutorial.go

Feature 添加阅读进度功能

---

internal/app/api/v1/badge.go
internal/app/api/v1/share.go
internal/app/cmd/config.demo.yaml
internal/app/config/config.go
internal/app/config/share.go
internal/app/dao/claim_badge_tweet.go
internal/app/dao/user_challenges.go
internal/app/model/claim_badge_tweet.go
internal/app/model/request/badge.go
internal/app/model/request/share.go
internal/app/model/response/share.go
internal/app/router/badge.go
internal/app/router/router.go
internal/app/router/share.go
internal/app/service/badge.go
internal/app/service/share.go
internal/job/service/quest_minter_test.go
internal/job/service/service_test.go

Add 添加统一处理空投功能

---

internal/app/api/v1/share.go
internal/app/cmd/config.demo.yaml
internal/app/config/config.go
internal/app/config/discord.go
internal/app/config/share.go
internal/app/dao/discord.go
internal/app/model/request/share.go
internal/app/model/response/share.go
internal/app/service/share.go
internal/app/utils/verify.go
internal/job/cmd/config.demo.yaml

Add 添加空投结果提醒、空投服务接口校验

---

internal/app/api/v1/judge.go
internal/app/cmd/config.demo.yaml
internal/app/config/judge.go
internal/app/initialize/judge.go
internal/app/router/judge.go
internal/app/router/router.go
internal/app/service/answer.go
internal/app/service/service.go

Fix 判题链接错误

---

internal/app/service/answer.go
internal/app/service/badge.go

Fix: 修复缺少判题参数

---

internal/app/api/v1/judge.go
internal/app/router/judge.go
internal/app/service/judge.go

Fix: 修复缺少接口

---

internal/app/service/answer.go
internal/app/service/judge.go

Fix 多次点击claim报错

---

internal/app/api/v1/challenge.go
internal/app/model/request/challenge.go
internal/app/model/user_challenge_log.go
internal/app/model/user_challenges.go
internal/app/router/challenge.go
internal/app/service/answer.go
internal/app/service/badge.go
internal/app/service/challenge.go
internal/job/dao/user_challenges.go
internal/job/service/quest_minter.go
internal/job/service/quest_minter_test.go
internal/job/service/transaction.go
internal/judge/api/v1/run.go
internal/judge/service/build.go
internal/judge/service/forge.go
internal/judge/service/hardhat.go
internal/judge/service/move.go
internal/judge/service/solidity.go

Fix 修复统计数据出错

---

internal/app/api/v1/quest.go
internal/app/dao/quest.go
internal/app/initialize/gorm_pgsql.go
internal/app/model/quest.go
internal/app/model/request/quest.go
internal/app/model/response/quest.go
internal/app/router/quest.go
internal/app/service/quest.go

Add 添加合辑功能

---

internal/app/dao/tutorial.go
internal/app/model/tutorial.go

https://github.com/decert-me/website/issues/225#issue-1893593977
@panyinglei

En: 教程排序改为按权重排序

---

internal/app/dao/quest.go
internal/app/model/response/quest.go

https://github.com/decert-me/website/issues/226#issue-1902415720
@panyinglei

Add 合辑接口添加合辑作者信息

---

internal/app/dao/claim_badge_tweet.go
internal/app/dao/discord.go
internal/app/model/request/badge.go
internal/app/model/request/share.go
internal/app/model/response/share.go
internal/app/service/badge.go
internal/app/service/share.go

https://github.com/decert-me/website/issues/230
@panyinglei

En: claim流程调整

---

internal/app/api/v1/meta.go
internal/app/dao/quest.go
internal/app/router/router.go
internal/app/service/meta.go

Feature 添加社交分享 Meta 数据

---

internal/app/model/claim_badge_tweet.go
internal/app/model/response/quest.go
internal/app/model/transaction.go
internal/app/model/upload.go
internal/app/model/user_challenge_claim.go
internal/app/model/user_challenge_log.go
internal/app/model/user_challenges.go
internal/app/model/users.go

Fix 数据库用户地址长度和格式

---

internal/app/api/v1/ipfs.go
internal/app/utils/verify.go

Fix 无后缀文件上传成功

---

internal/app/api/v1/collection.go
internal/app/api/v1/ipfs.go
internal/app/api/v1/quest.go
internal/app/cmd/locale.json
internal/app/dao/collection.go
internal/app/dao/quest.go
internal/app/model/collection.go
internal/app/model/request/collection.go
internal/app/model/request/ipfs.go
internal/app/model/request/quest.go
internal/app/model/response/collection.go
internal/app/model/response/common.go
internal/app/router/collection.go
internal/app/router/quest.go
internal/app/router/router.go
internal/app/service/answer.go
internal/app/service/collection.go
internal/app/service/quest.go
internal/app/utils/answer.go
internal/app/utils/verify.go
internal/job/dao/collection.go
internal/job/service/badge.go
internal/job/service/quest.go

Feature 合集NFT功能

---

internal/app/service/ipfs.go

Fix 修复上传图片丢失Content-Type
@panyinglei

Fix 修复上传图片丢失Content-Type

---

internal/app/api/v1/ipfs.go
internal/app/api/v1/message.go
internal/app/api/v1/user.go
internal/app/dao/message.go
internal/app/dao/open_quest_perm.go
internal/app/dao/quest.go
internal/app/dao/user_challenge_log.go
internal/app/dao/user_challenges.go
internal/app/initialize/gorm.go
internal/app/model/admin_user.go
internal/app/model/open_quest_perm.go
internal/app/model/request/message.go
internal/app/model/response/challenge.go
internal/app/model/response/quest.go
internal/app/model/system_setting.go
internal/app/model/user_challenge_log.go
internal/app/model/user_message.go
internal/app/model/user_open_quest.go
internal/app/router/message.go
internal/app/router/router.go
internal/app/router/user.go
internal/app/service/answer.go
internal/app/service/challenge.go
internal/app/service/message.go
internal/app/service/user.go
internal/job/dao/user_challenges.go
internal/job/service/ipfs.go
internal/job/service/quest.go
internal/judge/deploy/Dockerfile

Feature 支持开放题功能

---

go.mod
go.sum
internal/app/api/v1/open_quest.go
internal/app/model/request/open_quest.go
internal/app/model/response/open_quest.go
internal/app/router/open_quest.go
internal/app/router/router.go
internal/app/service/answer.go
internal/app/service/badge.go
internal/app/service/challenge.go
internal/app/service/open_quest.go
internal/app/service/quest.go

添加用户审核开放题功能
@panyinglei 
影响
[app](https://github.com/decert-me/backend-go/tree/main/internal/app)

Feature 用户审核开放题功能

---

internal/judge/Dockerfile
internal/judge/service/build.go
internal/judge/service/forge.go
internal/judge/service/hardhat_test.go

Chore: 代码运行添加 openzeppelin 库

---

internal/app/service/social.go

Fix Discord绑定失败

---

internal/app/service/badge.go

Fix 领取NFT检测绑定信息错误

---

internal/app/service/open_quest.go

En 开放题按更新时间排序

---

internal/app/service/open_quest.go

Fix 修复用户对开放题评分，数据库没有记录分数
@panyinglei

Fix 修复用户对开放题评分，数据库没有记录分数

---

go.mod
go.sum
internal/judge/service/hardhat.go

Fix hardhat 编译失败报错提示
@panyinglei

Fix hardhat 编译失败报错提示

---

internal/app/README.md
internal/app/cmd/config.demo.yaml
internal/auth/README.md

En 完善 app 和 auth 模块的 README
@panyinglei

En 完善 app 和 auth 模块的 README

---

internal/judge/service/solidity.go

En 添加获取标准答案失败日志提示
@panyinglei 
影响judge

En 添加获取标准答案失败日志提示

---

internal/app/api/v1/collection.go
internal/app/api/v1/quest.go
internal/app/api/v1/user.go
internal/app/dao/collection.go
internal/app/dao/quest.go
internal/app/dao/user_challenges.go
internal/app/initialize/gorm.go
internal/app/model/collection_translated.go
internal/app/model/quest_translated.go
internal/app/model/request/challenge.go
internal/app/model/request/quest.go
internal/app/model/request/user.go
internal/app/model/response/quest.go
internal/app/router/user.go
internal/app/service/answer.go
internal/app/service/quest.go

Feature 挑战、合辑多语言支持
@panyinglei

Feature 挑战、合辑多语言支持

---

internal/app/dao/quest.go

Fix 开放题评分没有分数

---

internal/app/api/v1/collection.go
internal/app/api/v1/quest.go
internal/app/dao/collection.go
internal/app/dao/quest.go
internal/app/model/request/collection.go
internal/app/model/request/quest.go
internal/app/model/response/collection.go
internal/app/model/response/quest.go
internal/app/router/collection.go
internal/app/router/quest.go
internal/app/service/collection.go
internal/app/service/quest.go

Feature 排行榜功能

---

internal/app/dao/collection.go
internal/app/dao/quest.go

Fix 排行榜 Holders 列表排序错误
@panyinglei

Fix 排行榜 Holders 列表排序错误

---

internal/app/api/v1/zcloak.go
internal/app/cmd/config.demo.yaml
internal/app/cmd/locale.json
internal/app/config/config.go
internal/app/config/nft.go
internal/app/config/zcloak.go
internal/app/dao/quest.go
internal/app/dao/user_challenges.go
internal/app/dao/zcloak.go
internal/app/initialize/gorm.go
internal/app/model/nft_collection.go
internal/app/model/request/zcloak.go
internal/app/model/response/challenge.go
internal/app/model/response/quest.go
internal/app/model/zcloak_card.go
internal/app/model/zcloak_did.go
internal/app/router/router.go
internal/app/router/zcloak.go
internal/app/service/challenge.go
internal/app/service/open_quest.go
internal/app/service/zcloak.go

Feature ZCloak 链下证书功能

---

internal/app/api/v1/zcloak.go
internal/app/dao/open_quest.go
internal/app/dao/user_challenge_log.go
internal/app/model/request/zcloak.go
internal/app/router/zcloak.go
internal/app/service/zcloak.go

添加挑战直接生成zcloak card功能
@panyinglei

Add 挑战直接生成zcloak card

---

internal/app/initialize/gorm.go
internal/app/model/open_quest_user_perm.go
internal/app/model/user_open_quest.go
internal/app/service/answer.go
internal/app/service/challenge.go
internal/app/service/open_quest.go

添加指定账户去对具体挑战的开放题评分功能
@panyinglei

Feature 指定账户去对具体挑战的开放题评分

---

internal/app/api/v1/zcloak.go
internal/app/dao/zcloak.go
internal/app/model/request/zcloak.go
internal/app/router/zcloak.go
internal/app/service/zcloak.go

Add 获取did证书信息接口

---

internal/app/dao/user_challenges.go

Fix 个人中心列表数量不对等

---

internal/app/dao/zcloak.go
internal/app/model/request/ipfs.go
internal/app/service/challenge.go
internal/app/service/zcloak.go

did证书添加 media 图片数据
@panyinglei

Feature did证书添加 media 图片数据

---

internal/app/service/meta.go

Fix 修复分享到社交账号元数据丢失

---

go.mod
go.sum
internal/app/api/v1/quest.go
internal/app/model/response/quest.go
internal/app/router/quest.go
internal/app/service/quest.go

Add 添加获取用户分数接口

---

internal/app/api/v1/ipfs.go

en: add webp type in img-suffix

---

.github/workflows/deploy_api.yaml

add forece copy to file "decert-api", if not will failed if file exists

fix deploy_api.yaml

---

internal/app/model/response/open_quest.go

Fix 修复开放题列表报错

---

internal/job/dao/collection.go
internal/job/service/transaction.go

Fix 合集多链合约解析失败

---

internal/job/dao/collection.go

Fix 合集多链交易解析缺少链ID

---

internal/app/dao/user_challenge_claim.go
internal/app/service/collection.go
internal/app/service/collection_v2.go

Fix 领取合集判断是否完成错误

---

internal/app/api/v1/social.go
internal/app/assets/email_en.html
internal/app/assets/locale.json
internal/app/router/social.go
internal/app/service/social.go

Chore 邮箱验证码国际化

---

internal/app/api/v1/open_quest.go
internal/app/api/v2/open_quest.go
internal/app/model/request/open_quest.go
internal/app/model/response/open_quest.go
internal/app/router/open_quest_v2.go
internal/app/router/router.go
internal/app/service/open_quest.go
internal/app/service/open_quest_v2.go

开放题评分列表逻辑调整
https://github.com/decert-me/website/issues/390
@panyinglei

En 开放题评分列表逻辑调整

---

internal/job/dao/translated.go
internal/job/service/badge.go
internal/job/service/quest.go

Fix 修改挑战清除翻译

---

internal/app/model/response/open_quest.go
internal/app/service/answer.go
internal/app/service/badge.go
internal/app/service/badge_v2.go
internal/app/service/challenge.go
internal/app/service/open_quest.go
internal/app/service/open_quest_v2.go
internal/app/service/zcloak.go

Add 开放题评分分数接口

---

internal/app/api/v1/user.go
internal/app/api/v2/open_quest.go
internal/app/dao/admin_user.go
internal/app/dao/tag.go
internal/app/model/response/open_quest.go
internal/app/model/tag.go
internal/app/model/users.go
internal/app/model/users_tag.go
internal/app/service/open_quest_v2.go
internal/app/service/user.go

Feature 用户标签显示

---

internal/app/api/v1/tutorial.go
internal/app/dao/tutorial.go
internal/app/model/request/tutorial.go
internal/app/service/tutorial.go

过滤无挑战/教程的标签
https://github.com/orgs/decert-me/projects/2/views/1?pane=issue&itemId=69437770
@0xdwong

En 过滤无挑战/教程的标签

---

internal/app/api/v1/statistics.go
internal/app/dao/statistics.go
internal/app/model/request/statistics.go
internal/app/model/response/statistics.go
internal/app/router/router.go
internal/app/router/statistics.go
internal/app/service/statistics.go

Add 获取地址数据信息的接口

---

go.mod
go.sum
internal/app/api/v1/social.go
internal/app/api/v1/tutorial.go
internal/app/api/v1/user.go
internal/app/assets/locale.json
internal/app/dao/collection.go
internal/app/dao/quest.go
internal/app/dao/social.go
internal/app/dao/users.go
internal/app/model/request/social.go
internal/app/model/response/social.go
internal/app/router/social.go
internal/app/service/answer.go
internal/app/service/badge_v2.go
internal/app/service/ipfs.go
internal/app/service/meta.go
internal/app/service/open_quest_v2.go
internal/app/service/quest.go
internal/app/service/quest_v2.go
internal/app/service/social.go
internal/app/service/user.go
internal/app/service/zcloak.go
internal/auth/service/github.go
internal/auth/service/service.go
internal/auth/service/wechat.go

增加换绑社交账号功能
https://github.com/decert-me/website/issues/428
@0xdwong

Feature  换绑社交账号

---

internal/app/api/v1/social.go
internal/app/api/v2/quest.go
internal/app/assets/locale.json
internal/app/dao/users.go
internal/app/model/request/social.go
internal/app/model/response/user.go
internal/app/router/social.go
internal/app/service/quest_v2.go
internal/app/service/social.go
internal/app/service/user.go

微信绑定替换删除绑定信息和添加取消绑定替换接口
@0xdwong

Fix 微信绑定替换删除绑定信息

---

internal/app/api/v2/quest.go
internal/app/assets/locale.json
internal/app/model/response/user.go
internal/app/service/quest_v2.go
internal/app/service/user.go

只有管理员才能发布挑战
https://github.com/decert-me/website/issues/437
@0xdwong

Add 只有管理员才能发布挑战

---

internal/app/dao/claim_badge_tweet.go
internal/app/dao/collection.go
internal/app/dao/user_challenge_claim.go

Fix 合集挑战领取状态

---

internal/app/dao/collection.go

修复合辑内挑战内容重复出现
https://github.com/decert-me/backend-go/issues/152
@0xdwong

Fix 合辑内挑战内容重复出现

---

internal/app/dao/quest.go
internal/app/model/request/quest.go
internal/app/service/quest.go

Add 修改挑战分类

---

internal/app/dao/collection.go
internal/app/model/response/collection.go

Fix 合集 Badge Token ID

---

internal/app/model/tutorial.go

Fix 更新数据库模型

---

internal/app/model/response/open_quest.go
internal/app/service/open_quest_v2.go

Add 开放题上次分数和次数
